-- Caso Banco Arboleda
-- Esquema base para Supabase / PostgreSQL

create extension if not exists pgcrypto;

create table if not exists usuarios (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  email text not null unique,
  password_hash text not null,
  clave_online_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists cuentas (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references usuarios(id) on delete cascade,
  numero_cuenta text not null unique,
  alias text not null,
  saldo numeric(12,2) not null default 0,
  moneda text not null default 'PEN',
  created_at timestamptz not null default now()
);

create table if not exists operadores (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists servicios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null,
  activo boolean not null default true
);

create table if not exists recargas (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references usuarios(id) on delete cascade,
  cuenta_id uuid not null references cuentas(id) on delete cascade,
  numero_celular text not null,
  operador_id bigint not null references operadores(id) on delete restrict,
  monto numeric(10,2) not null,
  estado text not null default 'EXITOSA',
  created_at timestamptz not null default now()
);

create table if not exists pagos_servicio (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references usuarios(id) on delete cascade,
  cuenta_id uuid not null references cuentas(id) on delete cascade,
  servicio_id bigint not null references servicios(id) on delete restrict,
  codigo_referencia text not null,
  monto numeric(10,2) not null,
  estado text not null default 'EXITOSA',
  created_at timestamptz not null default now()
);

create table if not exists transferencias (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references usuarios(id) on delete cascade,
  cuenta_origen_id uuid not null references cuentas(id) on delete cascade,
  cuenta_destino_id uuid not null references cuentas(id) on delete cascade,
  monto numeric(10,2) not null,
  estado text not null default 'EXITOSA',
  created_at timestamptz not null default now(),
  constraint transferencias_cuentas_distintas check (cuenta_origen_id <> cuenta_destino_id)
);

create index if not exists idx_cuentas_usuario_id on cuentas(usuario_id);
create index if not exists idx_recargas_usuario_id on recargas(usuario_id);
create index if not exists idx_recargas_cuenta_id on recargas(cuenta_id);
create index if not exists idx_pagos_servicio_usuario_id on pagos_servicio(usuario_id);
create index if not exists idx_pagos_servicio_cuenta_id on pagos_servicio(cuenta_id);
create index if not exists idx_transferencias_usuario_id on transferencias(usuario_id);
